### ISSUE TITLE
[2.03] @value rules

### ISSUE THREAD

**Issue by Ocre42** [IATI/IATI-Rulesets#148]
The `@value` must be **omitted** for qualitative measures, must be **included** for non-qualitative measures and should be a valid number for all non-qualitative measures.

- `iati-activities/iati-activity/result/indicator/baseline/@value`
- `iati-activities/iati-activity/result/indicator/period/target/@value`
- `iati-activities/iati-activity/result/indicator/period/actual/@value`

**Comment by samuele-mattiuzzo** [comment]
Work will start once #149 has been reviewed

**Comment by samuele-mattiuzzo** [comment]
Simpler explanation:

if `@value` exists for the above elements, then `@value` must be a valid number

**Comment by andylolz** [comment]
> The `@value` […] must be **included** for non-qualitative measures

That’s covered by these existing rules:
https://github.com/IATI/IATI-Rulesets/blob/8ed0cb4ece9b216f18dde0b64b50031f6c719e52/rulesets/standard.json#L258-L278

> should be a valid number for all non-qualitative measures

That’s covered by the new rule added in ffc50389

> The `@value` must be **omitted** for qualitative measures

I don’t think this bit is covered.

**Comment by samuele-mattiuzzo** [comment]
> > The `@value` must be **omitted** for qualitative measures
> 
> I don’t think this bit is covered.

So tricky bit here: `non-qualitative` can only be checked once we retrieve the value and assess that it is not a`number()` type, in which case it can be assumed as `Fail` because we managed to retrieve `@value` and assess that it's also a number.

Now, my reasoning was: we can't check `@value does not exist if it's not a number` unless we check `@value` (in which case, we're already halfway through a potential failure). I figured that checking `@value exists AND is_a_number(@value)` would automatically exclude the rest, because they both need to be true at the same time. Thoughts? Does it make sense?

Happy to update it next week and give it a bit more thinking.

It was a convoluted rule I had a bit of discussions with Amy about.

**Comment by samuele-mattiuzzo** [comment]
Update: discussing it with @amy-silcock

**Comment by samuele-mattiuzzo** [comment]
I was wondering as well wether `@value` could have provided the information needed by itself or if it was dependant on another element's value. Thanks to Amy, that was clarified and the follow up improvement issue has been raised 👍
