### ISSUE TITLE
Text versions of rules (generated by text.py) are sometimes difficult to understand

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Rulesets#155]
For instance, these rules are quite difficult to make sense of:
http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/result/indicator/#rules

![screenshot 2019-03-04 at 09 59 03](https://user-images.githubusercontent.com/464193/53725592-38140a80-3e64-11e9-8701-0a34191fe985.png)

It might be preferable to instead include a text explanation of each rule inside standard.json, rather than attempting to auto-generate it.

**Comment by samuele-mattiuzzo** [comment]
Hear hear! Especially because most of those auto generated parts are well explained from where we took the Rules ourselves, so no idea why it has to obfuscate the meaning that much either.

The per-rule description in `standard.json` is def the way to go. I'm keen on having one generic description per rule, rather than a per `case` description (so, instead of saying `path/to/element/@attribute must match path/to/other/@attribute`, it would just say "the value of this element must match the value of that other element") although I'm not entirely sure that would make it any better.

**Comment by andylolz** [comment]
The example provided here is no longer relevant, because these rules have since been removed. Closing
